import {
  ARROW_DOWN_ICON,
  ARROW_UP_ICON,
  ARROW_LEFT_ICON,
  ARROW_RIGHT_ICON,
  COMMENT_ICON,
  COPY_ICON,
  CHECK_ICON,
  DOWNLOAD_ICON,
  EYE_ICON,
  INFO_ICON,
  LANGUAGE_ICON,
  UPLOAD_ICON,
  PENCIL_ICON,
  PALETTE_ICON,
  PLUS_ICON,
  SEARCH_ICON,
  SUN_ICON,
  DASH_ICON,
  SCREEN_FULL_ICON,
  THREE_BARS_ICON,
  WINDOW_ICON,
  X_ICON,
} from '../iconography.js';

/** Every package icon by name, for the renderer. The browser imports single icons instead (`iconography.ts`). */
export const PACKAGE_ICON_PATHS = {
  'arrow-down': ARROW_DOWN_ICON.path,
  'arrow-up': ARROW_UP_ICON.path,
  'arrow-left': ARROW_LEFT_ICON.path,
  'arrow-right': ARROW_RIGHT_ICON.path,
  comment: COMMENT_ICON.path,
  copy: COPY_ICON.path,
  check: CHECK_ICON.path,
  download: DOWNLOAD_ICON.path,
  eye: EYE_ICON.path,
  info: INFO_ICON.path,
  language: LANGUAGE_ICON.path,
  upload: UPLOAD_ICON.path,
  pencil: PENCIL_ICON.path,
  palette: PALETTE_ICON.path,
  plus: PLUS_ICON.path,
  search: SEARCH_ICON.path,
  sun: SUN_ICON.path,
  dash: DASH_ICON.path,
  'screen-full': SCREEN_FULL_ICON.path,
  'three-bars': THREE_BARS_ICON.path,
  window: WINDOW_ICON.path,
  x: X_ICON.path,
} as const;
