/** English package strings. */

import type { EditionStrings, PackageStrings } from '../localization.js';
import { editionKind } from './edition-kind.js';

const EDITION_KINDS_EN: Readonly<Record<string, string>> = {
  'markdown:paragraph': 'paragraph',
  'markdown:heading': 'heading',
  'markdown:list': 'list',
  'markdown:table': 'table',
  'markdown:code': 'code',
  'markdown:blockquote': 'quote',
  'markdown:thematic-break': 'divider',
  'directive:diagram': 'diagram',
  'directive:chart': 'chart',
  'directive:callout': 'callout',
  'directive:disclosure': 'disclosure',
  'directive:card': 'card',
  'directive:cards': 'cards',
  'directive:section': 'section',
};

const editionEn: EditionStrings = {
  region: 'Changes since the previous edition',
  summary: (edition, totals) => {
    const parts = [
      totals.changed > 0
        ? `${totals.changed} block${totals.changed === 1 ? '' : 's'} changed in ${totals.sections} section${totals.sections === 1 ? '' : 's'}`
        : undefined,
      totals.added > 0 ? `${totals.added} added` : undefined,
      totals.removed > 0 ? `${totals.removed} removed` : undefined,
      totals.moved > 0 ? `${totals.moved} moved` : undefined,
    ].filter((part): part is string => part !== undefined);
    return `Edition ${edition}. Since the previous one: ${parts.length === 0 ? 'sections renamed or reordered' : parts.join(', ')}.`;
  },
  unchanged: (edition) => `Edition ${edition}. Nothing changed since the previous build.`,
  localeAdded: (edition) => `Edition ${edition}. This language version is new.`,
  show: 'Show changes',
  previous: 'Previous',
  next: 'Next',
  list: 'List of changes',
  button: 'Changes',
  panelTitle: 'Changes since the previous edition',
  beforeSections: 'Page opening',
  empty: 'No changes.',
  added: 'New',
  changed: 'Changed',
  rewritten: 'Rewritten',
  removed: 'Removed',
  moved: 'Moved',
  renamed: 'Renamed',
  movedFrom: (section) => `from “${section}”`,
  movedTo: (section) => `Moved to “${section}” →`,
  movedHere: 'Moved →',
  sectionAdded: 'new section',
  sectionRemoved: (title) => `Section removed: “${title}”`,
  sectionRenamed: (previous) => `was “${previous}”`,
  sectionMoved: 'section moved',
  contentsMark: 'has changes',
  containsChanges: 'contains changes',
  previousText: 'Previous wording',
  removedBlock: (kind, excerpt) => `Removed: ${kind}${excerpt === '' ? '' : ` “${excerpt}”`}`,
  kind: editionKind(EDITION_KINDS_EN, 'block'),
  node: (label) => `node “${label}”`,
  edge: (from, to) => `link “${from}” → “${to}”`,
  removedParts: (parts) => `Removed: ${parts.join('; ')}.`,
  point: (series, label) => (series === '' ? `“${label}”` : `“${label}” (${series})`),
  pointChanged: (point, previous, value) => `${point}: ${previous} → ${value}`,
  pointsChanged: (parts) => `Changed: ${parts.join('; ')}.`,
  pointsAdded: (parts) => `Added: ${parts.join('; ')}.`,
  pointsRemoved: (parts) => `Removed: ${parts.join('; ')}.`,
  image: (alt) => (alt === '' ? 'image' : `image “${alt}”`),
};

export const EN_STRINGS: PackageStrings = {
  formatNumber: (value) =>
    new Intl.NumberFormat('en', { maximumFractionDigits: 6, useGrouping: true }).format(value),
  skipToContent: 'Skip to content',
  hideContents: 'Hide contents',
  showContents: 'Show contents',
  openContents: 'Open contents',
  closeContents: 'Close contents',
  contents: 'Contents',
  current: 'Current / ',
  language: 'Language',
  languageName: (locale) => (locale === 'ru' ? 'Russian' : 'English'),
  reportAttribution: 'Made with Agentic Report',
  review: 'Review',
  scheme: 'Light or dark',
  theme: 'Theme',
  chooseTheme: 'Choose theme',
  toggleScheme: 'Switch light and dark scheme',
  documentContents: 'Document contents',
  onThisPage: 'On this page',
  close: 'Close',
  copy: 'Copy',
  copied: 'Copied',
  copyUnavailable: 'Copy unavailable',
  glossary: 'Glossary',
  viewFullDefinition: 'View full definition',
  download: (label) => `Download ${label}`,
  details: 'Details',
  tab: (number) => `Tab ${number}`,
  contentSections: 'Content sections',
  dialog: 'Dialog',
  openDialog: 'Open dialog',
  showDetails: 'Show details',
  scrollableGallery: 'Scrollable gallery',
  compareBefore: 'Before',
  pauseVideo: 'Pause video',
  playVideo: 'Play video',
  expandVideo: 'Expand',
  videoChapters: 'Chapters',
  titleSlide: 'Title slide',
  slideCounter: (slide, total) => `Slide ${slide} of ${total}`,
  previousSlide: 'Previous slide',
  nextSlide: 'Next slide',
  slides: 'Slides',
  slide: 'slide',
  enterFullScreen: 'Full screen',
  exitFullScreen: 'Exit full screen',
  titleScreen: 'Title screen',
  screens: 'Screens',
  screenLabel: (screen, total, title) => `Screen ${screen} of ${total}: ${title}`,
  sceneStep: (step, total) => `Step ${step} of ${total}`,
  pauseMotion: 'Pause motion',
  compareAfter: 'After',
  comparePosition: (before, after) => `Divider between ${before} and ${after}`,
  severity: { blocking: 'Blocking', major: 'Major', minor: 'Minor', note: 'Note' },
  findingsSummary: 'Findings by severity',
  cardStatus: { good: 'Good', watch: 'Watch', risk: 'At risk' },
  diffSummary: (added, removed) =>
    `${added} ${added === 1 ? 'line' : 'lines'} added, ${removed} removed`,
  filterItems: 'Filter items',
  filter: 'Filter',
  toggleContent: 'Toggle content',
  increment: 'Increment',
  items: (count) => `${count} ${count === 1 ? 'item' : 'items'}`,
  chart: 'Chart',
  series: 'Series',
  value: 'Value',
  legend: 'Legend',
  diagram: 'Diagram',
  node: (n) => `Node ${n}`,
  participant: (n) => `Participant ${n}`,
  timeline: 'Timeline',
  event: 'Event',
  data: 'Data',
  messagesInOrder: 'Messages in order',
  none: 'none',
  to: 'to',
  diagramText: {
    flowLead: (nodes, layers) => `Nodes: ${nodes}; flow layers: ${layers}.`,
    sequenceLead: (participants, messages) =>
      `Participants: ${participants}; messages: ${messages}.`,
    groups: 'Groups',
    group: (label, members) => `“${label}”: ${members.join(', ')}`,
    layers: 'Layers along the flow',
    forward: 'Connections along the flow',
    backward: 'Connections back against the flow',
    participants: 'Participants from left to right',
    participantsList: 'Participants',
    insideItself: 'inside itself',
    transcript: 'Diagram in words',
  },
  figureViewer: {
    open: 'Open',
    openLabel: (title) => `Open “${title}” full screen`,
    dialog: (title) => `${title}, full screen`,
    table: 'Table',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit to screen',
    hint: 'Drag to move; pinch, Ctrl + scroll or double-click to zoom; arrows move, + and − zoom, 0 fits.',
  },
  diagramLayouts: {
    switcher: 'Diagram layout',
    down: 'Top to bottom',
    right: 'Left to right',
    orthogonal: 'Right angles',
  },
  edgeKinds: {
    call: 'call',
    data: 'data or values',
    event: 'event or callback',
    dependency: 'dependency or creation',
  },
  reviewWorkspace: 'Review workspace',
  reviewThisReport: 'Review this report',
  noThreads: 'No discussion threads yet',
  discussionSelected: 'Discussion for selected block',
  noteForSelection: 'Note for selected text',
  createNote: 'Create note',
  viewThread: 'View thread',
  currentNotes: 'Notes in this report',
  noMessages: 'No messages yet.',
  newMessage: 'New message',
  addMessage: 'Add message',
  saveMessage: 'Save message',
  cancelEdit: 'Cancel edit',
  resolveThread: 'Resolve thread',
  reopenThread: 'Reopen thread',
  previousThreads: 'Threads from the previous revision',
  importReview: 'Import review',
  exportReview: 'Export review.json',
  exitReview: 'Exit review',
  openReview: 'Open review',
  closeReview: 'Close review',
  reviewUnavailable: 'Review unavailable',
  enterMessage: 'Enter a message for the selected text.',
  agent: 'Agent',
  you: 'You',
  edit: 'Edit',
  resolved: 'resolved',
  unresolved: 'unresolved',
  prior: 'Prior',
  historical: 'Historical',
  threadsSummary: (total, open) =>
    `${total} ${total === 1 ? 'thread' : 'threads'} · unresolved: ${open}`,
  reviewBinding: (binding) =>
    ({ exact: 'exact', changed: 'changed', missing: 'missing', ambiguous: 'ambiguous' })[binding],
  reviewTargetFallback: (kind) =>
    kind === 'markdown:thematic-break' ? 'Thematic break' : 'Report block',
  openDiscussion: (label) => `Open discussion for ${label}`,
  openNote: (label) => `Open note for “${label}”`,
  resolveFor: (resolved, label) => `${resolved ? 'Reopen' : 'Resolve'} thread for ${label}`,
  fileTooLarge: (bytes) => `Review files must be no larger than ${bytes} bytes.`,
  differentRevision: 'This review belongs to a different report revision.',
  unsupportedReview: 'Version 1 reviews are unsupported. Export a current review from this page.',
  importFailed: 'Review import failed.',
  multipleCurrentSegments: 'Imported review contains more than one current segment for a thread.',
  unknownCurrentTarget:
    'Imported review contains a current target that is not part of this report revision.',
  invalidSelectionAnchor:
    'Imported review contains a selected-text anchor that does not match this report revision.',
  unanswered: 'Not answered',
  answered: 'Answered',
  copyResponse: 'Copy response',
  downloadResponse: 'Download response.json',
  importResponse: 'Import response',
  responseCopied: 'Response copied',
  responseCopyUnavailable: 'Clipboard unavailable; download the response file instead.',
  responseImportFailed: 'Response import failed. Existing answers were preserved.',
  responseDifferentForm: 'This response belongs to a different or outdated form.',
  responseUnsupported: 'This response file uses an unsupported contract version.',
  responseFileTooLarge: (bytes) => `Response files must be no larger than ${bytes} bytes.`,
  responseInvalidValues: 'Correct invalid response values before exporting.',
  responseReady: 'Response file imported.',
  unassigned: 'Unassigned',
  itemComment: 'Comment',
  openOriginal: 'Open original',
  moveUp: 'Move up',
  moveDown: 'Move down',
  assignTo: (label) => `Assign to ${label}`,
  edition: editionEn,
};
