/** Russian package strings. */

import type { EditionStrings, PackageStrings } from '../localization.js';
import { editionKind } from './edition-kind.js';

const EDITION_KINDS_RU: Readonly<Record<string, string>> = {
  'markdown:paragraph': 'абзац',
  'markdown:heading': 'заголовок',
  'markdown:list': 'список',
  'markdown:table': 'таблица',
  'markdown:code': 'код',
  'markdown:blockquote': 'цитата',
  'markdown:thematic-break': 'разделитель',
  'directive:diagram': 'схема',
  'directive:chart': 'график',
  'directive:callout': 'выноска',
  'directive:disclosure': 'раскрывающийся блок',
  'directive:card': 'карточка',
  'directive:cards': 'карточки',
  'directive:section': 'раздел',
};

const editionRu: EditionStrings = {
  region: 'Изменения с прошлой редакции',
  summary: (edition, totals) => {
    const parts = [
      totals.changed > 0
        ? `${russianCountForm(totals.changed, 'изменён', 'изменено', 'изменено')} ${totals.changed} ${russianCountForm(totals.changed, 'блок', 'блока', 'блоков')} в ${totals.sections} ${russianCountForm(totals.sections, 'разделе', 'разделах', 'разделах')}`
        : undefined,
      totals.added > 0
        ? `${russianCountForm(totals.added, 'добавлен', 'добавлено', 'добавлено')} ${totals.added}`
        : undefined,
      totals.removed > 0
        ? `${russianCountForm(totals.removed, 'удалён', 'удалено', 'удалено')} ${totals.removed}`
        : undefined,
      totals.moved > 0
        ? `${russianCountForm(totals.moved, 'перемещён', 'перемещено', 'перемещено')} ${totals.moved}`
        : undefined,
    ].filter((part): part is string => part !== undefined);
    return `Редакция ${edition}. С прошлой: ${parts.length === 0 ? 'разделы переименованы или переставлены' : parts.join(', ')}.`;
  },
  unchanged: (edition) => `Редакция ${edition}. С прошлой сборки ничего не изменилось.`,
  localeAdded: (edition) => `Редакция ${edition}. Эта языковая версия новая.`,
  show: 'Показывать изменения',
  previous: 'Предыдущее',
  next: 'Следующее',
  list: 'Список изменений',
  button: 'Изменения',
  panelTitle: 'Изменения с прошлой редакции',
  beforeSections: 'Начало страницы',
  empty: 'Изменений нет.',
  added: 'Новое',
  changed: 'Изменено',
  rewritten: 'Переписано',
  removed: 'Удалено',
  moved: 'Перемещено',
  renamed: 'Переименовано',
  movedFrom: (section) => `из раздела «${section}»`,
  movedTo: (section) => `Перемещено в раздел «${section}» →`,
  movedHere: 'Перемещено →',
  sectionAdded: 'новый раздел',
  sectionRemoved: (title) => `Удалён раздел «${title}»`,
  sectionRenamed: (previous) => `было «${previous}»`,
  sectionMoved: 'раздел перемещён',
  contentsMark: 'есть изменения',
  containsChanges: 'внутри есть изменения',
  previousText: 'Прежняя редакция',
  removedBlock: (kind, excerpt) => `Удалено: ${kind}${excerpt === '' ? '' : ` «${excerpt}»`}`,
  kind: editionKind(EDITION_KINDS_RU, 'блок'),
  node: (label) => `узел «${label}»`,
  edge: (from, to) => `связь «${from}» → «${to}»`,
  removedParts: (parts) => `Удалено: ${parts.join('; ')}.`,
  point: (series, label) => (series === '' ? `«${label}»` : `«${label}» (${series})`),
  pointChanged: (point, previous, value) => `${point}: ${previous} → ${value}`,
  pointsChanged: (parts) => `Изменено: ${parts.join('; ')}.`,
  pointsAdded: (parts) => `Добавлено: ${parts.join('; ')}.`,
  pointsRemoved: (parts) => `Удалено: ${parts.join('; ')}.`,
  image: (alt) => (alt === '' ? 'картинка' : `картинка «${alt}»`),
};

export const RU_STRINGS: PackageStrings = {
  formatNumber: (value) =>
    new Intl.NumberFormat('ru', { maximumFractionDigits: 6, useGrouping: true }).format(value),
  skipToContent: 'Перейти к содержимому',
  hideContents: 'Скрыть содержание',
  showContents: 'Показать содержание',
  openContents: 'Открыть содержание',
  closeContents: 'Закрыть содержание',
  contents: 'Содержание',
  current: 'Сейчас / ',
  language: 'Язык',
  languageName: (locale) => (locale === 'ru' ? 'Русский' : 'Английский'),
  reportAttribution: 'Создано с Agentic Report',
  review: 'Ревью',
  scheme: 'Схема',
  theme: 'Тема',
  chooseTheme: 'Выбрать тему',
  toggleScheme: 'Переключить светлую и тёмную схему',
  documentContents: 'Содержание документа',
  onThisPage: 'На этой странице',
  close: 'Закрыть',
  copy: 'Копировать',
  copied: 'Скопировано',
  copyUnavailable: 'Копирование недоступно',
  glossary: 'Глоссарий',
  viewFullDefinition: 'Открыть полное определение',
  download: (label) => `Скачать ${label}`,
  details: 'Подробности',
  tab: (number) => `Вкладка ${number}`,
  contentSections: 'Разделы содержимого',
  dialog: 'Диалог',
  openDialog: 'Открыть диалог',
  showDetails: 'Показать подробности',
  scrollableGallery: 'Прокручиваемая галерея',
  compareBefore: 'До',
  pauseVideo: 'Остановить видео',
  playVideo: 'Запустить видео',
  expandVideo: 'Развернуть',
  videoChapters: 'Главы',
  titleSlide: 'Титульный слайд',
  slideCounter: (slide, total) => `Слайд ${slide} из ${total}`,
  previousSlide: 'Предыдущий слайд',
  nextSlide: 'Следующий слайд',
  slides: 'Слайды',
  slide: 'слайд',
  enterFullScreen: 'На весь экран',
  exitFullScreen: 'Выйти из полноэкранного режима',
  titleScreen: 'Первый экран',
  screens: 'Экраны',
  screenLabel: (screen, total, title) => `Экран ${screen} из ${total}: ${title}`,
  sceneStep: (step, total) => `Шаг ${step} из ${total}`,
  pauseMotion: 'Остановить движение',
  compareAfter: 'После',
  comparePosition: (before, after) => `Граница между «${before}» и «${after}»`,
  severity: { blocking: 'Блокирует', major: 'Существенно', minor: 'Мелочь', note: 'Заметка' },
  findingsSummary: 'Находки по серьёзности',
  cardStatus: { good: 'В норме', watch: 'Под наблюдением', risk: 'Под угрозой' },
  diffSummary: (added, removed) => `Добавлено строк: ${added}, удалено: ${removed}`,
  filterItems: 'Фильтровать элементы',
  filter: 'Фильтр',
  toggleContent: 'Переключить содержимое',
  increment: 'Увеличить',
  chart: 'Диаграмма',
  series: 'Ряд',
  value: 'Значение',
  legend: 'Легенда',
  diagram: 'Схема',
  node: (n) => `Узел ${n}`,
  participant: (n) => `Участник ${n}`,
  timeline: 'Хронология',
  event: 'Событие',
  data: 'Данные',
  messagesInOrder: 'Сообщения по порядку',
  none: 'нет',
  to: 'к',
  diagramText: {
    flowLead: (nodes, layers) => `Узлов: ${nodes}, слоёв потока: ${layers}.`,
    sequenceLead: (participants, messages) =>
      `Участников: ${participants}, сообщений: ${messages}.`,
    groups: 'Группы',
    group: (label, members) => `«${label}»: ${members.join(', ')}`,
    layers: 'Слои по потоку',
    forward: 'Связи по потоку',
    backward: 'Обратные связи',
    participants: 'Участники слева направо',
    participantsList: 'Участники',
    insideItself: 'внутри себя',
    transcript: 'Схема словами',
  },
  figureViewer: {
    open: 'Открыть',
    openLabel: (title) => `Открыть «${title}» во весь экран`,
    dialog: (title) => `${title} во весь экран`,
    table: 'Таблица',
    zoomIn: 'Приблизить',
    zoomOut: 'Отдалить',
    fit: 'Вписать в экран',
    hint: 'Тяните, чтобы сдвинуть; щипок, Ctrl + прокрутка или двойное касание — масштаб; стрелки сдвигают, + и − меняют масштаб, 0 вписывает.',
  },
  diagramLayouts: {
    switcher: 'Раскладка схемы',
    down: 'Сверху вниз',
    right: 'Слева направо',
    orthogonal: 'Прямые углы',
  },
  edgeKinds: {
    call: 'вызов',
    data: 'данные или значения',
    event: 'событие или обратный вызов',
    dependency: 'зависимость или создание',
  },
  items: (count) => `${count} ${russianCountForm(count, 'элемент', 'элемента', 'элементов')}`,
  reviewWorkspace: 'Пространство ревью',
  reviewThisReport: 'Ревью отчёта',
  noThreads: 'Обсуждений пока нет',
  discussionSelected: 'Обсуждение выбранного блока',
  noteForSelection: 'Заметка к выделенному тексту',
  createNote: 'Создать заметку',
  viewThread: 'Открыть тред',
  currentNotes: 'Заметки в этом отчёте',
  noMessages: 'Сообщений пока нет.',
  newMessage: 'Новое сообщение',
  addMessage: 'Добавить сообщение',
  saveMessage: 'Сохранить сообщение',
  cancelEdit: 'Отменить редактирование',
  resolveThread: 'Закрыть обсуждение',
  reopenThread: 'Возобновить обсуждение',
  previousThreads: 'Обсуждения предыдущей редакции',
  importReview: 'Импортировать ревью',
  exportReview: 'Экспортировать review.json',
  exitReview: 'Выйти из ревью',
  openReview: 'Открыть ревью',
  closeReview: 'Закрыть ревью',
  reviewUnavailable: 'Ревью недоступно',
  enterMessage: 'Введите сообщение для выделенного текста.',
  agent: 'Агент',
  you: 'Вы',
  edit: 'Изменить',
  resolved: 'закрыто',
  unresolved: 'открыто',
  prior: 'Предыдущее',
  historical: 'Историческое',
  threadsSummary: (total, open) =>
    `${total} ${russianCountForm(total, 'обсуждение', 'обсуждения', 'обсуждений')} · открыто: ${open}`,
  reviewBinding: (binding) =>
    ({ exact: 'точно', changed: 'изменено', missing: 'не найдено', ambiguous: 'неоднозначно' })[
      binding
    ],
  reviewTargetFallback: (kind) =>
    kind === 'markdown:thematic-break' ? 'Разделитель' : 'Блок отчёта',
  openDiscussion: (label) => `Открыть обсуждение: ${label}`,
  openNote: (label) => `Открыть заметку к «${label}»`,
  resolveFor: (resolved, label) => `${resolved ? 'Возобновить' : 'Закрыть'} обсуждение: ${label}`,
  fileTooLarge: (bytes) => `Размер файла ревью не должен превышать ${bytes} байт.`,
  differentRevision: 'Это ревью относится к другой редакции отчёта.',
  unsupportedReview:
    'Ревью версии 1 не поддерживаются. Экспортируйте актуальное ревью с этой страницы.',
  importFailed: 'Не удалось импортировать ревью.',
  multipleCurrentSegments:
    'Импортированное ревью содержит несколько текущих сегментов одного обсуждения.',
  unknownCurrentTarget:
    'Импортированное ревью содержит текущую цель, которой нет в этой редакции отчёта.',
  invalidSelectionAnchor:
    'Импортированное ревью содержит привязку к выделенному тексту, которой нет в этой редакции отчёта.',
  unanswered: 'Нет ответа',
  answered: 'Есть ответ',
  copyResponse: 'Копировать ответ',
  downloadResponse: 'Скачать response.json',
  importResponse: 'Импортировать ответ',
  responseCopied: 'Ответ скопирован',
  responseCopyUnavailable: 'Буфер недоступен; скачайте файл ответа.',
  responseImportFailed: 'Не удалось импортировать ответ. Введённые ответы сохранены.',
  responseDifferentForm: 'Ответ относится к другой или устаревшей форме.',
  responseUnsupported: 'Версия файла ответа не поддерживается.',
  responseFileTooLarge: (bytes) => `Размер файла ответа не должен превышать ${bytes} байт.`,
  responseInvalidValues: 'Исправьте недопустимые значения ответа перед экспортом.',
  responseReady: 'Файл ответа импортирован.',
  unassigned: 'Не распределено',
  itemComment: 'Комментарий',
  openOriginal: 'Открыть оригинал',
  moveUp: 'Поднять',
  moveDown: 'Опустить',
  assignTo: (label) => `Переместить в «${label}»`,
  edition: editionRu,
};

function russianCountForm(count: number, singular: string, paucal: string, plural: string): string {
  if (count % 10 === 1 && count % 100 !== 11) return singular;
  if ([2, 3, 4].includes(count % 10) && ![12, 13, 14].includes(count % 100)) return paucal;
  return plural;
}
